version: "3"


services :
    # webサーバーの定義
    mt-web-server:
        image: httpd
        ports:
          - "22280:80"
        volumes:
            - "./app-source:/usr/local/apache2/htdocs/"
            - "./sites-enabled/httpd.conf:/usr/local/apache2/conf/httpd.conf"
        container_name: mt-web-server
        environment:
            TZ: Asia/Tokyo
        links:
            - mt-app-server:mt-app-server
        networks:
            - mt_network

    # アプリケーションサーバーの定義
    mt-app-server:
        build: "./app-docker-file"
        ports:
            - "19000:9000"
        volumes:
            - "./app-ini:/usr/local/etc/php"
            - "./app-source:/var/www/html/application"
        container_name: mt-app-server
        environment:
            TZ: Asia/Tokyo
        networks:
            - mt_network

    # DBサーバーの定義
    mt-db-server:
        image: mariadb
        restart: always
        volumes:
            - "maria_db:/var/lib/mysql"
            - "./mysql-cnf:/etc/mysql/conf.d"
        ports:
            - "13306:3306"
        environment:
            - MYSQL_DATABASE=mt
            - MYSQL_USER=mt
            - MYSQL_PASSWOR=mt
            - MYSQL_ROOT_PASSWORD=mt

networks:
    mt_network:
        external: true

volumes:
    maria_db:
        external: true